name: step_goal_widget
description: A Flutter package for Wear OS that provides a custom widget to track steps and display progress toward a daily step goal.
version: 0.0.1
homepage: https://github.com/yourusername/step_goal_widget

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^3.0.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

